### ISSUE TITLE
Byte widget size

### ISSUE THREAD

**Issue by nickbattam** [willrogers/cssgen#53]
The Byte widget is defaults to 'alarm sensitive'. 

This property forces an invisible 2px border around the outside of the widget (separate to the drawn LED border) meaning the widget is smaller than intended.

I propose changing the default to `border_alarm_sensitive=False`

**Comment by nickbattam** [comment]
It is also defaulting to non-packed; which is usually not what you want and the opposite of what is done by the EDL-OPI converter.
I propose changing the default to `led_packed=True`

**Comment by willrogers** [comment]
These sound fine to me.
